DROP TABLE IF EXISTS users;
CREATE TABLE users (
	uid INTEGER PRIMARY KEY NOT NULL,
	name CHAR(50) NOT NULL
);

DROP TABLE IF EXISTS characters;
CREATE TABLE characters (
	charid INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	owner INTEGER NOT NULL,
	name CHAR(50) NOT NULL,
	ctype INTEGER NOT NULL,
	data TEXT NOT NULL
);
